# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userMembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nbCoins',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CreateMember',
        ),
    ]
