# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMembers', '0004_auto_20170818_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
