# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMembers', '0006_auto_20170819_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='age',
        ),
    ]
