# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMembers', '0007_remove_profil_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nbVotes',
            field=models.IntegerField(default=0),
        ),
    ]
