# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOpponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchStarting', models.DateField()),
                ('equipeOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipeOne', to='tournamentGames.TeamGGC')),
                ('equipeTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipeTwo', to='tournamentGames.TeamGGC')),
                ('gameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentGames.GameName')),
            ],
        ),
    ]
