# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0003_auto_20170822_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchopponents',
            name='matchName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
