# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournamentGames', '0004_matchopponents_matchname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prognostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentGames.MatchOpponents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentGames.TeamGGC')),
            ],
        ),
    ]
