# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0005_prognostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prognostic',
            name='match',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prognostic',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prognostic',
            name='vote',
            field=models.CharField(max_length=100),
        ),
    ]
