# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0007_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
