# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0008_matchresult_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='match',
            new_name='matchNumber',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='test',
        ),
    ]
