# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0010_matchresult_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='maj',
            field=models.BooleanField(default=False),
        ),
    ]
