# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0013_auto_20170901_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prognostic',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentGames.TeamGGC'),
        ),
    ]
