# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 15:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0015_auto_20170907_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchopponents',
            name='equipeOne',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameName', chained_model_field='gameName', on_delete=django.db.models.deletion.CASCADE, related_name='equipeOne', to='tournamentGames.TeamGGC'),
        ),
    ]
