# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 14:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0016_auto_20170913_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchopponents',
            name='equipeOne',
        ),
        migrations.RemoveField(
            model_name='matchopponents',
            name='equipeTwo',
        ),
        migrations.AddField(
            model_name='matchopponents',
            name='equipe',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameName', chained_model_field='teamGame', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='equipeTwo', to='tournamentGames.TeamGGC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='winner',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='matchNumber', chained_model_field='equipe', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournamentGames.TeamGGC'),
        ),
    ]
