# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentGames', '0018_auto_20170915_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='gameName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournamentGames.GameName'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='winner',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameName', chained_model_field='teamGame', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournamentGames.TeamGGC'),
        ),
    ]
